### PR TITLE
Added a new modem: MikroTik R11e-LTE6

### PR DESCRIPTION
**Pull request by Kodo-kakaku**
Done:
- The modem was added according to the "Luat LTE Module documentation AT Command Interface User Manual Rev1.0";
- Testing was performed on the basis of the router "MikroTik RBM33G" plat.ver."OpenWrt-18.06.7";
- Code optimization performed;
- Fixed typos;
- The main code was not changed.

### CODE REVIEW

**Comment by koshev-msk** [comment]
Thank for you PR!
So...  I will ask several clarifying questions:
First.  Possible  AT command answer for showing Secondary Carrier band LTE cat.6 modem?
Second. Possible AT commands answer the chip tempеrature?

**Comment by Kodo-kakaku** [comment]
Hi! 
The biggest problem is that MikroTik does not provide any official documentation for its modems, not all the commands from the documentation that I found are suitable... 
But I have now clarified some points and so in order: 
1.Regarding the aggregation of carrier frequencies, I found the command:

>  9.6 AT*BANDIND Description Indicates the current band

 to which the modem responds:

> AT*BANDIND?
*BANDIND: 0, 3, 7

OK


I think this is the second frequency, but as you can see the data has already been converted to band, so you will have to do the reverse conversion to frequency so that the web interface will then convert all this back to band. I'll take care of it. 
2. There are no commands for getting the chip temperature in the documentation, so I didn't include it. If I can find anything on the subject of temperature, I will definitely add it. 
3. You can learn more about what you need to do with WCDMA / UMTS and GSM / EDGE?

**Comment by koshev-msk** [comment]
https://mikrotik.com/product/r11e_lte
https://mikrotik.com/product/r11e_lte6
R11e-LTE and R11e-LTE6 support 2-nd and 3-rd generation networks. RSSI for GSM/EDGE, and EcIO/RSSI for UMTS/WCDMA  must included visible values.

**Comment by Kodo-kakaku** [comment]
One of these days I will try to fix these bugs:
* Doens't show RSSI/ECiO on WCDMA/UMTS networks. Need changes.
* Doens't show RSSI on GSM networks. Need changes.
All day I tried to find information on how to get the temperature status of the MikroTik chip, but there is no information anywhere... I tend to believe that this function was not provided by the manufacturer.

**Pull request merged**
